import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "background": "#131313",
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#ebbbb4",
        "outline": "#b18780",
        "outline-variant": "#603e39",
        "primary": "#ffb4a8",
        "on-primary": "#690100",
        "primary-container": "#ff5540",
        "on-primary-container": "#5c0000",
        "secondary": "#9ccaff",
        "on-secondary": "#003257",
        "secondary-container": "#2295ed",
        "tertiary": "#acc7ff",
        "tertiary-container": "#488fff",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "surface-variant": "#353534",
        "surface-tint": "#ffb4a8",
      },
      spacing: {
        "sidebar-width": "240px",
        "sidebar-collapsed-width": "72px",
        "gutter": "16px",
        "margin-desktop": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config;
